const APP_MODULES = [
  {
    code: 'TALENT_ACQUISITION',
    name: 'Acquisition des talents et onboarding',
    description: "Recrutement, pipeline candidat et integration d'arrivee.",
  },
  {
    code: 'DOCUMENT_ADMIN',
    name: 'Gestion documentaire et administrative',
    description: 'Documents RH, contrats et dossiers administratifs.',
  },
  {
    code: 'PAYROLL_COMPENSATION',
    name: 'Gestion de la paie et des remunerations',
    description: 'Paie, avantages, primes et elements de remuneration.',
  },
  {
    code: 'TIME_ATTENDANCE',
    name: 'Gestion des mouvements et presences',
    description: 'Pointage, presence, retards et mouvements.',
  },
  {
    code: 'LEAVE_WORKFLOW',
    name: 'Gestion des conges et validation',
    description: 'Demandes de conges et workflow de validation.',
  },
  {
    code: 'PERFORMANCE_360',
    name: 'Gestion des performances 360',
    description: 'Objectifs, feedback continu et evaluations 360.',
  },
];

const PERMISSIONS = [
  { code: 'auth.reset-password', name: 'Reinitialiser les mots de passe', description: 'Declencher ou assister une reinitialisation.' },
  { code: 'user.create', name: 'Creer des utilisateurs', description: 'Creer un compte utilisateur depuis l administration.' },
  { code: 'user.read', name: 'Lire les utilisateurs', description: 'Consulter la liste et les fiches utilisateurs.' },
  { code: 'user.update', name: 'Modifier les utilisateurs', description: 'Mettre a jour les informations d un utilisateur.' },
  { code: 'user.suspend', name: 'Suspendre les utilisateurs', description: 'Suspendre ou reactiver un compte utilisateur.' },
  { code: 'role.read', name: 'Lire les roles', description: 'Consulter les roles disponibles.' },
  { code: 'role.assign', name: 'Attribuer les roles', description: 'Changer le role principal d un utilisateur.' },
  { code: 'permission.read', name: 'Lire les permissions', description: 'Consulter les permissions systeme.' },
  { code: 'permission.assign', name: 'Attribuer les permissions', description: 'Ajouter des permissions directes a un utilisateur.' },
  { code: 'module.read', name: 'Lire les modules', description: 'Consulter les modules disponibles dans l application RH.' },
  { code: 'module.assign', name: 'Attribuer les modules', description: 'Accorder des modules a un role ou a un utilisateur.' },
  { code: 'profile.read', name: 'Lire son profil', description: 'Consulter son profil utilisateur.' },
  { code: 'profile.update', name: 'Mettre a jour son profil', description: 'Mettre a jour certaines informations personnelles.' },
  { code: 'talent.request.read', name: 'Lire les demandes de recrutement', description: 'Consulter les demandes de recrutement.' },
  { code: 'talent.request.create', name: 'Creer les demandes de recrutement', description: 'Creer une demande de recrutement.' },
  { code: 'talent.request.update', name: 'Modifier les demandes de recrutement', description: 'Mettre a jour le statut ou les donnees d une demande de recrutement.' },
  { code: 'talent.job.read', name: 'Lire les offres de recrutement', description: 'Consulter les offres et postes ouverts.' },
  { code: 'talent.job.create', name: 'Creer les offres de recrutement', description: 'Creer une offre ou un poste a pourvoir.' },
  { code: 'talent.job.update', name: 'Modifier les offres de recrutement', description: 'Mettre a jour les offres et leurs statuts.' },
  { code: 'talent.candidate.read', name: 'Lire les candidats', description: 'Consulter la base candidats.' },
  { code: 'talent.candidate.create', name: 'Creer les candidats', description: 'Ajouter un candidat dans la base.' },
  { code: 'talent.candidate.update', name: 'Modifier les candidats', description: 'Mettre a jour les donnees d un candidat.' },
  { code: 'talent.application.read', name: 'Lire les candidatures', description: 'Consulter les candidatures et le pipeline.' },
  { code: 'talent.application.create', name: 'Creer les candidatures', description: 'Associer un candidat a une offre.' },
  { code: 'talent.application.update', name: 'Modifier les candidatures', description: 'Mettre a jour le pipeline et les statuts.' },
  { code: 'talent.interview.read', name: 'Lire les entretiens', description: 'Consulter les entretiens planifies.' },
  { code: 'talent.interview.create', name: 'Creer les entretiens', description: 'Planifier un entretien.' },
  { code: 'talent.interview.update', name: 'Modifier les entretiens', description: 'Mettre a jour le statut ou le feedback d un entretien.' },
  { code: 'talent.offer.read', name: 'Lire les offres d embauche', description: 'Consulter les propositions d embauche.' },
  { code: 'talent.offer.create', name: 'Creer les offres d embauche', description: 'Creer une proposition d embauche.' },
  { code: 'talent.offer.update', name: 'Modifier les offres d embauche', description: 'Mettre a jour le statut d une offre d embauche.' },
  { code: 'talent.onboarding.read', name: 'Lire les plans d onboarding', description: 'Consulter les parcours d integration.' },
  { code: 'talent.onboarding.create', name: 'Creer les plans d onboarding', description: 'Creer un plan d onboarding.' },
  { code: 'talent.onboarding.update', name: 'Modifier les plans d onboarding', description: 'Mettre a jour les plans et taches d onboarding.' },
  { code: 'talent.dashboard.read', name: 'Lire le dashboard recrutement', description: 'Consulter les indicateurs du recrutement et onboarding.' },
  { code: 'talent.document.read', name: 'Lire les documents talent', description: 'Consulter les documents candidats et onboarding.' },
  { code: 'talent.document.create', name: 'Ajouter des documents talent', description: 'Televerser des documents candidats et onboarding.' },
  { code: 'talent.document.update', name: 'Modifier les documents talent', description: 'Mettre a jour les metadonnees documentaires talent.' },
  { code: 'performance.dashboard.read', name: 'Lire le dashboard performance', description: 'Consulter les indicateurs de performance, KPI et evaluation.' },
  { code: 'performance.options.read', name: 'Lire les options performance', description: 'Consulter les listes de support du module performance.' },
  { code: 'performance.cycle.read', name: 'Lire les campagnes performance', description: 'Consulter les cycles et campagnes de performance.' },
  { code: 'performance.cycle.create', name: 'Creer les campagnes performance', description: 'Creer un cycle ou une campagne de performance.' },
  { code: 'performance.cycle.update', name: 'Modifier les campagnes performance', description: 'Mettre a jour un cycle ou une campagne de performance.' },
  { code: 'performance.goal.read', name: 'Lire les objectifs performance', description: 'Consulter les objectifs individuels de performance.' },
  { code: 'performance.goal.create', name: 'Creer les objectifs performance', description: 'Creer un objectif individuel de performance.' },
  { code: 'performance.goal.update', name: 'Modifier les objectifs performance', description: 'Mettre a jour un objectif individuel de performance.' },
  { code: 'performance.review.read', name: 'Lire les evaluations performance', description: 'Consulter les evaluations et revues de performance.' },
  { code: 'performance.review.create', name: 'Creer les evaluations performance', description: 'Creer une evaluation ou revue de performance.' },
  { code: 'performance.review.update', name: 'Modifier les evaluations performance', description: 'Mettre a jour une evaluation ou revue de performance.' },
  { code: 'performance.feedback.read', name: 'Lire les feedbacks performance', description: 'Consulter les feedbacks continus et 360.' },
  { code: 'performance.feedback.create', name: 'Creer les feedbacks performance', description: 'Ajouter un feedback continu ou 360.' },
  { code: 'performance.training.read', name: 'Lire les plans de developpement', description: 'Consulter les actions de formation liees a la performance.' },
  { code: 'performance.training.create', name: 'Creer les plans de developpement', description: 'Creer une action de formation ou plan de developpement.' },
  { code: 'performance.training.update', name: 'Modifier les plans de developpement', description: 'Mettre a jour une action de formation ou plan de developpement.' },
];

const SYSTEM_ROLES = [
  {
    code: 'SUPER_ADMIN',
    name: 'Super Admin',
    description: "Controle complet de l'application et des acces.",
    permissionCodes: PERMISSIONS.map((permission) => permission.code),
    moduleCodes: APP_MODULES.map((moduleItem) => moduleItem.code),
  },
  {
    code: 'ADMIN',
    name: 'Admin',
    description: 'Administration fonctionnelle des utilisateurs et modules RH.',
    permissionCodes: [
      'auth.reset-password',
      'user.create',
      'user.read',
      'user.update',
      'user.suspend',
      'role.read',
      'role.assign',
      'permission.read',
      'permission.assign',
      'module.read',
      'module.assign',
      'profile.read',
      'profile.update',
      'talent.request.read',
      'talent.request.create',
      'talent.request.update',
      'talent.job.read',
      'talent.job.create',
      'talent.job.update',
      'talent.candidate.read',
      'talent.candidate.create',
      'talent.candidate.update',
      'talent.application.read',
      'talent.application.create',
      'talent.application.update',
      'talent.interview.read',
      'talent.interview.create',
      'talent.interview.update',
      'talent.offer.read',
      'talent.offer.create',
      'talent.offer.update',
      'talent.onboarding.read',
      'talent.onboarding.create',
      'talent.onboarding.update',
      'talent.dashboard.read',
      'talent.document.read',
      'talent.document.create',
      'talent.document.update',
      'performance.dashboard.read',
      'performance.options.read',
      'performance.cycle.read',
      'performance.cycle.create',
      'performance.cycle.update',
      'performance.goal.read',
      'performance.goal.create',
      'performance.goal.update',
      'performance.review.read',
      'performance.review.create',
      'performance.review.update',
      'performance.feedback.read',
      'performance.feedback.create',
      'performance.training.read',
      'performance.training.create',
      'performance.training.update',
    ],
    moduleCodes: APP_MODULES.map((moduleItem) => moduleItem.code),
  },
  {
    code: 'EMPLOYEE',
    name: 'Employe',
    description: 'Compte standard avec acces personnel limite.',
    permissionCodes: ['profile.read', 'profile.update'],
    moduleCodes: [],
  },
];

module.exports = {
  APP_MODULES,
  PERMISSIONS,
  SYSTEM_ROLES,
};
